name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v3
    - run: zip -r ./module.zip module.json packs/ 
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: './module.json'
        tag: latest